force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>Stores error details during a batch Apex job</description>
    <label>Error Log</label>
    <nameField>
        <label>Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Async_Apex_Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Async_Apex_Job_Id__c</fullName>
    <description>Apex Job Id</description>
    <inlineHelpText>Apex Job Id</inlineHelpText>
    <label>Async Apex Job Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Exception Message</description>
    <inlineHelpText>Exception Message</inlineHelpText>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/BatchApexErrorEventTriggerHandler.cls
public class BatchApexErrorEventTriggerHandler {
    public static void handleBatchErrorEvents(List<BatchApexErrorEvent> batchErrorList){
        List<Error_Log__c> errorLogList = new List<Error_Log__c>();
        
        for(BatchApexErrorEvent ev: batchErrorList){
            Error_Log__c log = new Error_Log__c ();
            log.Name = 'Batch Error';
            log.Async_Apex_Job_Id__c = ev.AsyncApexJobId;
            log.Message__c = ev.Message;
            errorLogList.add(log);
        }
        
        if(!errorLogList.isEmpty()){
            insert errorLogList;
        }
    }

}