force-app/main/default/objects/Product_Geo_Mapping__mdt/Product_Geo_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Metadata to map Products to the minimum permissible fly zones in different countries.</description>
    <label>Product Geo Mapping</label>
    <pluralLabel>Product Geo Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Product_Geo_Mapping__mdt/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <description>ISO Aplpha-2 code for countries</description>
    <inlineHelpText>Alpha-2 country code</inlineHelpText>
    <label>Country Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Geo_Mapping__mdt/fields/Permissible_Fly_Zone__c.field-meta.xml
<CustomField>
    <fullName>Permissible_Fly_Zone__c</fullName>
    <description>allowed area&apos;s for specific air craft</description>
    <label>Permissible Fly Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Recommended</fullName>
                <default>true</default>
                <label>Recommended</label>
            </value>
            <value>
                <fullName>Regulated</fullName>
            </value>
            <value>
                <fullName>Authorized</fullName>
            </value>
            <value>
                <fullName>Restricted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Geo_Mapping__mdt/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <label>Product Family</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProductZoningService.cls
@RestResource(urlMapping='/ProductZoning/*')
global with sharing class ProductZoningService {
    
    @HttpGet
    global static String doGet() {
        RestRequest req = RestContext.request;
        
        String countryCode = req.headers.get('CountryCode');
        String prodCode = req.params.get('ProductCode');
        
        if (String.isBlank(countryCode)) {
            countryCode = 'US';
        }
        
        if (String.isBlank(prodCode)) {
            return 'ProductCode is missing or doesn\'t exist';
        }
        
        List<Product2> prodLst = [SELECT Family FROM Product2 WHERE ProductCode = :prodCode];
        
        if (prodLst.isEmpty()) {
            return 'ProductCode is missing or doesn\'t exist';
        }
        
        List<Product_Geo_Mapping__mdt> pfz = [SELECT Permissible_Fly_Zone__c 
                                              FROM Product_Geo_Mapping__mdt 
                                              WHERE Product_Family__c = :prodLst[0].Family 
                                              AND Country_Code__c = :countryCode];
        
        if (pfz.isEmpty()) {
            return 'Confirm with the local authorities';
        } else {
            return pfz[0].Permissible_Fly_Zone__c;
        }
    }
}