force-app/main/default/objects/Asset/fields/Asset_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Asset_Identifier__c</fullName>
    <description>Unique Id for an asset.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique Id for an asset.</inlineHelpText>
    <label>Asset Identifier</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <description>Insurance claim filed by a customer</description>
    <label>Claim</label>
    <nameField>
        <displayFormat>C{0000000}</displayFormat>
        <label>Claim Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Insurance__c.field-meta.xml
<CustomField>
    <fullName>Insurance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insurance</label>
    <referenceTo>Insurance__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the insurance claim</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>Damage</fullName>
            </value>
            <value>
                <fullName>Loss</fullName>
            </value>
            <value>
                <fullName>Equipment</fullName>
            </value>
            <value>
                <fullName>Injury</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance__c/Insurance__c.object-meta.xml
<CustomObject>
    <description>Insurance details for aircraft</description>
    <label>Insurance</label>
    <nameField>
        <displayFormat>IS{0000000}</displayFormat>
        <label>Policy ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Insurance__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Shows whether the policy is active or not</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insurance__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Insurances</relationshipLabel>
    <relationshipName>Insurances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Insurance__c/fields/Coverage__c.field-meta.xml
<CustomField>
    <fullName>Coverage__c</fullName>
    <description>Types of coverage available</description>
    <label>Coverage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Comprehensive</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>Flyaway</fullName>
            </value>
            <value>
                <fullName>Equipment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AssetService.cls
@RestResource(urlMapping='/lost')
global with sharing class AssetService {

    @HttpPost
    global static String reportLostDevice(String assetIdentifier) {
        RestRequest req = RestContext.request;
        //RestResponse res = RestContext.response;
        //res.addHeader('Content-Type', 'application/json');
        
        if (String.isBlank(assetIdentifier)) {
            //res.statusCode = 400;
            return 'No device found.';
        }
        
        // Fetch the asset using assetIdentifier
        List<Asset> assets = [SELECT Id, Status FROM Asset WHERE Asset_Identifier__c = :assetIdentifier LIMIT 1];
        
        if(assets.size()>0){
            Asset asset = assets[0];
            asset.Status = 'Lost';
            update asset;
            
            // Fetch insurance policy for the asset
        	List<Insurance__c> insurances = [SELECT Id, Active__c, Coverage__c FROM Insurance__c WHERE Asset__c = :asset.Id AND Active__c = TRUE LIMIT 1];
            if(insurances.size()>0 && insurances[0].Coverage__c == 'Comprehensive'){
                List<Claim__c> claims = [SELECT Id,Name FROM Claim__c WHERE Insurance__c = :insurances[0].Id AND Type__c = 'Loss' LIMIT 1];
                if(claims.size()==0){
                    Claim__c newClaim = new Claim__c();
                    newClaim.Asset__c = asset.Id;
                    newClaim.Insurance__c = insurances[0].Id;
                    newClaim.Status__c = 'New';
                    newClaim.Type__c = 'Loss';
                    insert newClaim;
                    
                    Claim__c claimUpdated = [SELECT Id,Name FROM Claim__c WHERE Insurance__c = :insurances[0].Id AND Type__c = 'Loss' Order by CreatedDate DESC LIMIT 1 ];
                    return claimUpdated.Name;
                }else{
                    return claims[0].Name +' already filed.';
                }
            }else{
                return 'No coverage. Asset status adjusted to Lost.';
            }
            
            
           /* if (insurances.size()>0 && insurances[0].Coverage__c == 'Comprehensive') {
                // Check for existing loss claim
        		List<Claim__c> existingClaims = [SELECT Id, Name FROM Claim__c WHERE Asset__c = :asset.Id AND Type__c = 'Loss' LIMIT 1];
			
                if (!existingClaims.isEmpty()) {
                    return existingClaims[0].Name + ' already filed.';
                }else{
                    Claim__c newClaim = new Claim__c();
                    newClaim.Asset__c = asset.Id;
                    newClaim.Insurance__c = insurances[0].Id;
                    newClaim.Status__c = 'New';
                    newClaim.Type__c = 'Loss';
                    insert newClaim;
                    
                    Claim__c claimUpdated = [SELECT Id,Name FROM Claim__c WHERE Insurance__c = :insurances[0].Id AND Type__c = 'Loss' Order by CreatedDate DESC LIMIT 1 ];
                    return claimUpdated.Name;
                }
            }else {
                return 'No coverage. Asset status adjusted to Lost.';
            }*/
        }else {
            return 'No device found.';
        } 
    }
}