force-app/main/default/objects/Contact/fields/Pilot_Rating__c.field-meta.xml
<CustomField>
    <fullName>Pilot_Rating__c</fullName>
    <description>Overall Rating for the pilot</description>
    <inlineHelpText>Overall Rating for the pilot</inlineHelpText>
    <label>Pilot Rating</label>
    <precision>6</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mission__c/Mission__c.object-meta.xml
<CustomObject>
    <description>A job opportunity for a drone pilot interested in contracting.</description>
    <label>Mission</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Mission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mission</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mission__c/fields/Completion_Rating__c.field-meta.xml
<CustomField>
    <fullName>Completion_Rating__c</fullName>
    <description>Rate at completion</description>
    <inlineHelpText>Rate at completion</inlineHelpText>
    <label>Completion Rating</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mission__c/fields/Overall_Rating__c.field-meta.xml
<CustomField>
    <fullName>Overall_Rating__c</fullName>
    <description>Overall Rating</description>
    <inlineHelpText>Overall Rating</inlineHelpText>
    <label>Overall Rating</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mission__c/fields/Pilot__c.field-meta.xml
<CustomField>
    <fullName>Pilot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact who picks up the project.</description>
    <inlineHelpText>Contact who picks up the project.</inlineHelpText>
    <label>Pilot</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Mission</relationshipLabel>
    <relationshipName>Mission</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mission__c/fields/Safety_Incidents__c.field-meta.xml
<CustomField>
    <fullName>Safety_Incidents__c</fullName>
    <description>Number of safety incidents</description>
    <inlineHelpText>Number of safety incidents</inlineHelpText>
    <label>Safety Incidents</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mission__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the project.</description>
    <inlineHelpText>Status of the project.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Picked</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PilotRatingBatch.cls
global class PilotRatingBatch implements Database.Batchable<sObject> {
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        //Intentionally skip Pilot__r.Pilot_Rating__c field from the SOQL query to force the error: SObject row was retrieved via SOQL without querying the requested field: Mission__c.Pilot__r. 
        //Do not update the SOQL query for the solution.
        return Database.getQueryLocator('SELECT Id, Completion_Rating__c, Overall_Rating__c, Safety_Incidents__c, Pilot__c FROM Mission__c WHERE Status__c = \'Complete\'');
        
    }

    global void execute(Database.BatchableContext bc, List<Mission__c> scope) {
        List<Contact> contactList = new List<Contact>();
        for(Mission__c mission : scope){
            
            Double weightedCompletionRate = 0.3 * mission.Completion_Rating__c;
            Double weightedSafetyIncidents = -0.5 * mission.Safety_Incidents__c;

            Double newOverallRating;
            
            newOverallRating = mission.Pilot__r.Pilot_Rating__c+mission.Overall_Rating__c;
            mission.Pilot__r.Pilot_Rating__c = newOverallRating;
            
            contactList.add(mission.Pilot__r);
        }
        
        update contactList;
    }

    global void finish(Database.BatchableContext bc) {
    }


}